/*
 * Message API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"net/http"
	"errors"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService() DefaultApiServicer {
	return &DefaultApiService{}
}

// CreateMessage - Create a new message
func (s *DefaultApiService) CreateMessage(ctx context.Context, newMessage NewMessage) (ImplResponse, error) {
	// TODO - update CreateMessage with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(201, Message{}) or use other options such as http.Ok ...
	//return Response(201, Message{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("CreateMessage method not implemented")
}

// GetMessages - Get all messages
func (s *DefaultApiService) GetMessages(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetMessages with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	//TODO: Uncomment the next line to return response Response(200, []Message{}) or use other options such as http.Ok ...
	//return Response(200, []Message{}), nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetMessages method not implemented")
}
