/*
 * Message API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/jmoiron/sqlx"

	infra "github.com/GIT_USER_ID/GIT_REPO_ID/go/infra/mysql"
	"github.com/GIT_USER_ID/GIT_REPO_ID/go/model"
	"github.com/GIT_USER_ID/GIT_REPO_ID/go/repository"
)

// DefaultApiService is a service that implements the logic for the DefaultApiServicer
// This service should implement the business logic for every endpoint for the DefaultApi API.
// Include any external packages or services that will be required by this service.
type DefaultApiService struct {
	DB *sqlx.DB
}

// NewDefaultApiService creates a default api service
func NewDefaultApiService(DB *sqlx.DB) DefaultApiServicer {
	return &DefaultApiService{DB: DB}
}

// CreateMessage - Create a new message
// Saveを実行する
func (s *DefaultApiService) CreateMessage(ctx context.Context, newMessage NewMessage) (ImplResponse, error) {
	var f repository.MessageRepository = &infra.MessageRepository{DB: s.DB}

	message := &model.Message{Name: newMessage.Name, Message: newMessage.Message, CreatedAt: time.Now(), UpdatedAt: time.Now()}

	f.Save(message)

	// 生成されたMessageに詰め直す
	var msg Message
	m := Message{
		Name:      msg.Name,
		Message:   msg.Message,
		CreatedAt: msg.CreatedAt,
		UpdatedAt: msg.UpdatedAt,
	}

	return Response(http.StatusCreated, m), nil
}

// GetMessages - Get all messages
// Listを実行する
func (s *DefaultApiService) GetMessages(ctx context.Context) (ImplResponse, error) {
	var f repository.MessageRepository = &infra.MessageRepository{DB: s.DB}

	messages, err := f.List()
	if err != nil {
		fmt.Println(err)
	}

	// 生成されたMessageに詰め直す
	var messageList []Message
	for _, message := range messages {
		messageList = append(messageList, Message{
			Id:        message.ID,
			Name:      message.Name,
			Message:   message.Message,
			CreatedAt: message.CreatedAt,
			UpdatedAt: message.UpdatedAt,
		})
	}

	return Response(http.StatusOK, messageList), nil
}
