/*
 * Message API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Message struct {

	Id int32 `json:"id"`

	Name string `json:"name"`

	Message string `json:"message"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}

// AssertMessageRequired checks if the required fields are not zero-ed
func AssertMessageRequired(obj Message) error {
	elements := map[string]interface{}{
		"id": obj.Id,
		"name": obj.Name,
		"message": obj.Message,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseMessageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of Message (e.g. [][]Message), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseMessageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aMessage, ok := obj.(Message)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertMessageRequired(aMessage)
	})
}
