/*
 * Message API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type NewMessage struct {

	Name string `json:"name"`

	Message string `json:"message"`

	CreatedAt time.Time `json:"created_at"`

	UpdatedAt time.Time `json:"updated_at"`
}

// AssertNewMessageRequired checks if the required fields are not zero-ed
func AssertNewMessageRequired(obj NewMessage) error {
	elements := map[string]interface{}{
		"name": obj.Name,
		"message": obj.Message,
		"created_at": obj.CreatedAt,
		"updated_at": obj.UpdatedAt,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertRecurseNewMessageRequired recursively checks if required fields are not zero-ed in a nested slice.
// Accepts only nested slice of NewMessage (e.g. [][]NewMessage), otherwise ErrTypeAssertionError is thrown.
func AssertRecurseNewMessageRequired(objSlice interface{}) error {
	return AssertRecurseInterfaceRequired(objSlice, func(obj interface{}) error {
		aNewMessage, ok := obj.(NewMessage)
		if !ok {
			return ErrTypeAssertionError
		}
		return AssertNewMessageRequired(aNewMessage)
	})
}
